### ISSUE TITLE
Add stripe as a payment method

### ISSUE THREAD

**Issue by hakerdefo** [remjx/coindrop#145]
Payment method name: stripe

Payment method website: https://stripe.com

Link to icon in .SVG format (if available): https://d37ugbyn3rpeym.cloudfront.net/newsroom/brand-assets/Stripe-logo-kit.zip

**Comment by remjx** [comment]
hi @hakerdefo,

Stripe is different than the other payment methods Coindrop currently supports because receivers don't have a "Stripe address". Instead, we would have to integrate with their Stripe account which is possible but more complicated.

Can I ask: why do you want to add Stripe? Recurring payments, tax compliance, etc?

I could see it working as follows:
- Link your Stripe account
- When you click on "Stripe" button on the Coindrop page, display a credit card payment form 

^^ Is that what you're looking for?

The main downside of Stripe is that they charge a ~3% fee and it's more suited to business transactions. Right now Coindrop is more designed for donations & personal payments.

I'll definitely keep this open but I don't have plans to move on it immediately.

**Comment by hakerdefo** [comment]
Hi there @remjx 
PayPal doesn't allow users in India to send/pay money to other people in India as personal payments, while Stripe allows that.

> I could see it working as follows:

    Link your Stripe account
    When you click on "Stripe" button on the Coindrop page, display a credit card payment form

That's precisely what I want. It'll be great if you can implement this feature.
Cheers!!!

**Comment by remjx** [comment]
I signed up for Stripe and they cancelled the account 🤷  They said "[Coindrop] falls under our list of Restricted Businesses and Activities in our Services Agreement: https://stripe.com/terms" https://stripe.com/restricted-businesses

If there is another payment provider you would like to add, please open a new issue. 

Thanks!

**Comment by hakerdefo** [comment]
Thank you so much for your efforts @remjx. Really appreciate it. You tried.
Cheers!!!
