### ISSUE TITLE
"Error getting data, please try refreshing the page"

### ISSUE THREAD

**Issue by MagicLike** [remjx/coindrop#802]
**Describe the bug**

**To Reproduce**
1. Log-in after sign-up
2. See error

**Expected behavior**
See dashboard

**Screenshots**
![grafik](https://user-images.githubusercontent.com/82117109/190920780-4af23d47-441e-4011-8427-323f1dd8864f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 105.0b9

**Comment by remjx** [comment]
@MagicLike thanks for the report. I was not able to replicate this when I create a new account, it loads successfully for me.

I think it is caused by a false positive by App Check https://firebase.google.com/docs/app-check because I was getting this error in development and after I disabled App Check it started working again.

![image](https://user-images.githubusercontent.com/35121685/190924538-f85b86cc-fd4a-4883-9e4e-a50503768854.png)

I've disabled App Check for now - can you test if your Dashboard loads successfully now? https://coindrop.to/dashboard

**Comment by MagicLike** [comment]
Yes, it works now!
